export const PRESET_AVATARS = [
  { id: "avatar-1", name: "Alex", url: "https://api.dicebear.com/7.x/adventurer/svg?seed=Alex" },
  { id: "avatar-2", name: "Jordan", url: "https://api.dicebear.com/7.x/adventurer/svg?seed=Jordan" },
  { id: "avatar-3", name: "Taylor", url: "https://api.dicebear.com/7.x/adventurer/svg?seed=Taylor" },
  { id: "avatar-4", name: "Morgan", url: "https://api.dicebear.com/7.x/adventurer/svg?seed=Morgan" },
  { id: "avatar-5", name: "Robin", url: "https://api.dicebear.com/7.x/adventurer/svg?seed=Robin" },
  { id: "avatar-6", name: "Sam", url: "https://api.dicebear.com/7.x/adventurer/svg?seed=Sam" },
  { id: "avatar-7", name: "Casey", url: "https://api.dicebear.com/7.x/adventurer/svg?seed=Casey" },
  { id: "avatar-8", name: "Riley", url: "https://api.dicebear.com/7.x/adventurer/svg?seed=Riley" },
];

export const TEMPLATES = [
  {
    id: "sidebar-executive",
    name: "Sidebar Executive",
    desc: "A stunning two-column layout optimal for senior candidates.",
    layout: "sidebar",
    heading: "'Playfair Display',serif",
    body: "'Source Serif 4',serif",
    accent: "#2c3e50",
    panel: "#eef1f4",
    radius: 4,
    headingStyle: "plain",
    italic: false,
    headerAlign: "left",
    listStyle: "square",
    pageMargin: 32,
    itemSpacing: 24,
    jobLayout: "stacked",
    paper: "#ffffff",
    boxOpacity: 95,
    boxShadow: "medium",
    borderStyle: "none",
    backdropBlur: 4,
  },
  {
    id: "modern",
    name: "Modern Chic",
    desc: "Clean, elegant lines with a premium tech-focused accent color.",
    layout: "classic",
    heading: "'Poppins',sans-serif",
    body: "'Inter',sans-serif",
    accent: "#2f5d62",
    panel: "#ffffff",
    radius: 6,
    headingStyle: "underline",
    italic: false,
    headerAlign: "left",
    listStyle: "square",
    pageMargin: 48,
    itemSpacing: 24,
    jobLayout: "split",
    paper: "#ffffff",
    boxOpacity: 90,
    boxShadow: "none",
    borderStyle: "none",
    backdropBlur: 8,
  },
  {
    id: "classic",
    name: "Harvard Classic",
    desc: "The gold standard of investment banking and elite professional resumes.",
    layout: "classic",
    heading: "'Playfair Display',serif",
    body: "'Source Serif 4',serif",
    accent: "#4a3324",
    panel: "#ffffff",
    radius: 2,
    headingStyle: "plain",
    italic: true,
    headerAlign: "center",
    listStyle: "circle",
    pageMargin: 48,
    itemSpacing: 20,
    jobLayout: "split",
    paper: "#fdfbfa",
    boxOpacity: 95,
    boxShadow: "medium",
    borderStyle: "double",
    backdropBlur: 2,
  },
  {
    id: "traditional",
    name: "Traditional Professional",
    desc: "A reliable, highly structured grid-based layout.",
    layout: "classic",
    heading: "Georgia,serif",
    body: "Georgia,serif",
    accent: "#000000",
    panel: "#ffffff",
    radius: 0,
    headingStyle: "smallcaps",
    italic: false,
    headerAlign: "center",
    listStyle: "disc",
    pageMargin: 38,
    itemSpacing: 16,
    jobLayout: "split",
    paper: "#ffffff",
    boxOpacity: 0,
    boxShadow: "none",
    borderStyle: "none",
    backdropBlur: 0,
  },
  {
    id: "minimal",
    name: "Minimalist Slate",
    desc: "Zero clutter, premium spacing. Pushes content density.",
    layout: "classic",
    heading: "'Inter',sans-serif",
    body: "'Inter',sans-serif",
    accent: "#000000",
    panel: "#ffffff",
    radius: 0,
    headingStyle: "plain",
    italic: false,
    headerAlign: "left",
    listStyle: "disc",
    pageMargin: 38,
    itemSpacing: 16,
    jobLayout: "stacked",
    paper: "#ffffff",
    boxOpacity: 0,
    boxShadow: "none",
    borderStyle: "none",
    backdropBlur: 0,
  },
  {
    id: "sidebar-fresh",
    name: "Sidebar Fresh",
    desc: "A modern spin on the executive template.",
    layout: "sidebar",
    heading: "'Poppins',sans-serif",
    body: "'Nunito Sans',sans-serif",
    accent: "#0f766e",
    panel: "#eafaf7",
    radius: 12,
    headingStyle: "bar",
    italic: false,
    headerAlign: "left",
    listStyle: "disc",
    pageMargin: 38,
    itemSpacing: 16,
    jobLayout: "stacked",
    paper: "#ffffff",
    boxOpacity: 85,
    boxShadow: "deep",
    borderStyle: "dashed",
    backdropBlur: 12,
  },
];

export const TUTORIAL_STEPS = [
  {
    eyebrow: "Step 1 of 5",
    title: "Welcome to MYresume",
    body: "This whole page is your resume. There's no separate form — click directly on any text (like your name, up top) and start typing.",
  },
  {
    eyebrow: "Step 2 of 5",
    title: "Change the look anytime",
    body: "Open <b>🎨 Design</b> in the toolbar to swap templates, fonts, colors, spacing, or switch between a single-column and sidebar layout.",
  },
  {
    eyebrow: "Step 3 of 5",
    title: "Drag to reorder",
    body: "Grab the ⠿ handle on any section, job, bullet, or skill category to drag it into a new position.",
  },
  {
    eyebrow: "Step 4 of 5",
    title: "Add and remove freely",
    body: "Use the small <b>+</b> buttons to add sections, jobs, certifications, or bullets. Hover an item to reveal its <b>✕ remove</b> option.",
  },
  {
    eyebrow: "Step 5 of 5",
    title: "You're ready",
    body: "When it looks right, use <b>⬇ Export / Save as PDF</b> to print or save a PDF, or <b>💾 Save editable copy</b> to download an HTML file you can reopen and keep editing later.",
  },
];
